packages:
  - .
  - compute/*

allowBuilds:
  '@napi-rs/canvas': true
  better-sqlite3: true
  canvas: false
  core-js: false
  es5-ext: false
  esbuild: false
  ffmpeg-static: true
  onnxruntime-node: true
  sharp: false
  unrs-resolver: false

overrides:
  '@types/localforage': npm:empty-module@0.0.2
  '@xmldom/xmldom': ^0.9.8
  lodash: ^4.17.23

strictDepBuilds: false
