/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            natsConnected: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/exports/{artifactId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    artifactId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/sessions/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        storageUserId: string;
                        documentId: string;
                        documentVersion: number;
                        /** @enum {string} */
                        readerType: "pdf" | "epub" | "html";
                        settingsHash: string;
                        planObjectKey: string;
                        /** @enum {string} */
                        purpose: "live" | "export-document";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessionId: string;
                            session: unknown | null;
                            operation: {
                                opId: string;
                                subject: {
                                    /** @enum {string} */
                                    kind: "pdf_layout";
                                    documentId: string;
                                    namespace: string | null;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback";
                                    documentId: string;
                                    sessionId: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_plan";
                                    documentId: string;
                                    settingsHash: string;
                                    planSignature: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_export";
                                    documentId: string;
                                    artifactId: string;
                                    /** @enum {string} */
                                    format: "mp3" | "m4b";
                                } | {
                                    /** @enum {string} */
                                    kind: "document_preview";
                                    documentId: string;
                                    namespace: string | null;
                                    /** @enum {string} */
                                    previewKind: "card";
                                };
                                /** @enum {string} */
                                status: "queued" | "running" | "succeeded" | "failed";
                                queuedAt: number;
                                updatedAt: number;
                                startedAt?: number;
                                result?: unknown;
                                error?: {
                                    message: string;
                                    code?: string;
                                };
                                timing?: {
                                    queueWaitMs?: number;
                                    s3FetchMs?: number;
                                    computeMs?: number;
                                };
                                progress?: {
                                    totalPages: number;
                                    pagesParsed: number;
                                    currentPage?: number;
                                    /** @enum {string} */
                                    phase: "infer" | "merge";
                                } | {
                                    completedThroughOrdinal: number;
                                    completedCount: number;
                                    plannedCount: number;
                                } | {
                                    /** @enum {string} */
                                    phase: "assembling" | "transcoding" | "uploading";
                                    completedSegments: number;
                                    plannedSegments: number;
                                };
                            } | null;
                            progress: {
                                completedThroughOrdinal: number;
                                completedCount: number;
                                plannedCount: number;
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/sessions/{sessionId}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    minOrdinal?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/sessions/{sessionId}/cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ordinal: number;
                        expiresAt?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/cache/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        storageUserId: string;
                        documentId: string;
                        documentVersion?: number;
                        settingsHash?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            storageUserId: string;
                            documentId: string;
                            documentVersion: number | null;
                            settingsHash: string | null;
                            cacheEpoch: number;
                            invalidatedPlaybackSessions: number;
                            invalidatedSidecarCacheScopes: number;
                            invalidatedJobOperations: number;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/sessions/{sessionId}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Progressive MP3 audio stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Progressive MP3 audio byte range */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                416: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pdf-layout/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        documentId: string;
                        namespace: string | null;
                        documentObjectKey: string;
                        replaceToken?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            opId: string;
                            subject: {
                                /** @enum {string} */
                                kind: "pdf_layout";
                                documentId: string;
                                namespace: string | null;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback";
                                documentId: string;
                                sessionId: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_plan";
                                documentId: string;
                                settingsHash: string;
                                planSignature: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_export";
                                documentId: string;
                                artifactId: string;
                                /** @enum {string} */
                                format: "mp3" | "m4b";
                            } | {
                                /** @enum {string} */
                                kind: "document_preview";
                                documentId: string;
                                namespace: string | null;
                                /** @enum {string} */
                                previewKind: "card";
                            };
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed";
                            queuedAt: number;
                            updatedAt: number;
                            startedAt?: number;
                            result?: unknown;
                            error?: {
                                message: string;
                                code?: string;
                            };
                            timing?: {
                                queueWaitMs?: number;
                                s3FetchMs?: number;
                                computeMs?: number;
                            };
                            progress?: {
                                totalPages: number;
                                pagesParsed: number;
                                currentPage?: number;
                                /** @enum {string} */
                                phase: "infer" | "merge";
                            } | {
                                completedThroughOrdinal: number;
                                completedCount: number;
                                plannedCount: number;
                            } | {
                                /** @enum {string} */
                                phase: "assembling" | "transcoding" | "uploading";
                                completedSegments: number;
                                plannedSegments: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/document-previews/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        documentId: string;
                        namespace: string | null;
                        /** @enum {string} */
                        documentType: "pdf" | "epub";
                        sourceObjectKey: string;
                        sourceLastModifiedMs: number;
                        /** @enum {string} */
                        previewKind: "card";
                        rendererVersion?: string;
                        targetWidth?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            opId: string;
                            subject: {
                                /** @enum {string} */
                                kind: "pdf_layout";
                                documentId: string;
                                namespace: string | null;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback";
                                documentId: string;
                                sessionId: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_plan";
                                documentId: string;
                                settingsHash: string;
                                planSignature: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_export";
                                documentId: string;
                                artifactId: string;
                                /** @enum {string} */
                                format: "mp3" | "m4b";
                            } | {
                                /** @enum {string} */
                                kind: "document_preview";
                                documentId: string;
                                namespace: string | null;
                                /** @enum {string} */
                                previewKind: "card";
                            };
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed";
                            queuedAt: number;
                            updatedAt: number;
                            startedAt?: number;
                            result?: unknown;
                            error?: {
                                message: string;
                                code?: string;
                            };
                            timing?: {
                                queueWaitMs?: number;
                                s3FetchMs?: number;
                                computeMs?: number;
                            };
                            progress?: {
                                totalPages: number;
                                pagesParsed: number;
                                currentPage?: number;
                                /** @enum {string} */
                                phase: "infer" | "merge";
                            } | {
                                completedThroughOrdinal: number;
                                completedCount: number;
                                plannedCount: number;
                            } | {
                                /** @enum {string} */
                                phase: "assembling" | "transcoding" | "uploading";
                                completedSegments: number;
                                plannedSegments: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/sessions/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userId: string;
                        storageUserId: string;
                        documentId: string;
                        documentVersion: number;
                        /** @enum {string} */
                        readerType: "pdf" | "epub" | "html";
                        settingsHash: string;
                        settingsJson: unknown;
                        planning: {
                            selectedOrdinal?: number;
                            maxBlockLength?: number;
                            enforceSourceBoundaries?: boolean;
                            language?: string;
                            documentSource?: {
                                namespace: string | null;
                                skipBlockKinds?: string[];
                                /** @enum {string} */
                                extent: "section" | "document";
                                isPlainText?: boolean;
                            };
                        };
                        sessionId: string;
                        planObjectKey: string;
                        generationRunId?: string;
                        expiresAt?: number;
                        aheadWindow?: number;
                        /** @enum {string} */
                        backgroundExtent?: "section" | "document";
                        /** @enum {string} */
                        generationExtent?: "window" | "document";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            opId: string;
                            subject: {
                                /** @enum {string} */
                                kind: "pdf_layout";
                                documentId: string;
                                namespace: string | null;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback";
                                documentId: string;
                                sessionId: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_plan";
                                documentId: string;
                                settingsHash: string;
                                planSignature: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_export";
                                documentId: string;
                                artifactId: string;
                                /** @enum {string} */
                                format: "mp3" | "m4b";
                            } | {
                                /** @enum {string} */
                                kind: "document_preview";
                                documentId: string;
                                namespace: string | null;
                                /** @enum {string} */
                                previewKind: "card";
                            };
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed";
                            queuedAt: number;
                            updatedAt: number;
                            startedAt?: number;
                            result?: unknown;
                            error?: {
                                message: string;
                                code?: string;
                            };
                            timing?: {
                                queueWaitMs?: number;
                                s3FetchMs?: number;
                                computeMs?: number;
                            };
                            progress?: {
                                totalPages: number;
                                pagesParsed: number;
                                currentPage?: number;
                                /** @enum {string} */
                                phase: "infer" | "merge";
                            } | {
                                completedThroughOrdinal: number;
                                completedCount: number;
                                plannedCount: number;
                            } | {
                                /** @enum {string} */
                                phase: "assembling" | "transcoding" | "uploading";
                                completedSegments: number;
                                plannedSegments: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/plans/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        userId: string;
                        storageUserId: string;
                        documentId: string;
                        documentVersion: number;
                        /** @enum {string} */
                        readerType: "pdf" | "epub" | "html";
                        settingsHash: string;
                        settingsJson: unknown;
                        planning: {
                            selectedOrdinal?: number;
                            maxBlockLength?: number;
                            enforceSourceBoundaries?: boolean;
                            language?: string;
                            documentSource?: {
                                namespace: string | null;
                                skipBlockKinds?: string[];
                                /** @enum {string} */
                                extent: "section" | "document";
                                isPlainText?: boolean;
                            };
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            opId: string;
                            subject: {
                                /** @enum {string} */
                                kind: "pdf_layout";
                                documentId: string;
                                namespace: string | null;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback";
                                documentId: string;
                                sessionId: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_plan";
                                documentId: string;
                                settingsHash: string;
                                planSignature: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_export";
                                documentId: string;
                                artifactId: string;
                                /** @enum {string} */
                                format: "mp3" | "m4b";
                            } | {
                                /** @enum {string} */
                                kind: "document_preview";
                                documentId: string;
                                namespace: string | null;
                                /** @enum {string} */
                                previewKind: "card";
                            };
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed";
                            queuedAt: number;
                            updatedAt: number;
                            startedAt?: number;
                            result?: unknown;
                            error?: {
                                message: string;
                                code?: string;
                            };
                            timing?: {
                                queueWaitMs?: number;
                                s3FetchMs?: number;
                                computeMs?: number;
                            };
                            progress?: {
                                totalPages: number;
                                pagesParsed: number;
                                currentPage?: number;
                                /** @enum {string} */
                                phase: "infer" | "merge";
                            } | {
                                completedThroughOrdinal: number;
                                completedCount: number;
                                plannedCount: number;
                            } | {
                                /** @enum {string} */
                                phase: "assembling" | "transcoding" | "uploading";
                                completedSegments: number;
                                plannedSegments: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/exports/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        artifactId: string;
                        sessionId: string;
                        userId: string;
                        storageUserId: string;
                        documentId: string;
                        documentVersion: number;
                        /** @enum {string} */
                        readerType: "pdf" | "epub" | "html";
                        settingsHash: string;
                        settingsJson: unknown;
                        planObjectKey: string;
                        /** @enum {string} */
                        format: "mp3" | "m4b";
                        speed: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            opId: string;
                            subject: {
                                /** @enum {string} */
                                kind: "pdf_layout";
                                documentId: string;
                                namespace: string | null;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback";
                                documentId: string;
                                sessionId: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_plan";
                                documentId: string;
                                settingsHash: string;
                                planSignature: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_export";
                                documentId: string;
                                artifactId: string;
                                /** @enum {string} */
                                format: "mp3" | "m4b";
                            } | {
                                /** @enum {string} */
                                kind: "document_preview";
                                documentId: string;
                                namespace: string | null;
                                /** @enum {string} */
                                previewKind: "card";
                            };
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed";
                            queuedAt: number;
                            updatedAt: number;
                            startedAt?: number;
                            result?: unknown;
                            error?: {
                                message: string;
                                code?: string;
                            };
                            timing?: {
                                queueWaitMs?: number;
                                s3FetchMs?: number;
                                computeMs?: number;
                            };
                            progress?: {
                                totalPages: number;
                                pagesParsed: number;
                                currentPage?: number;
                                /** @enum {string} */
                                phase: "infer" | "merge";
                            } | {
                                completedThroughOrdinal: number;
                                completedCount: number;
                                plannedCount: number;
                            } | {
                                /** @enum {string} */
                                phase: "assembling" | "transcoding" | "uploading";
                                completedSegments: number;
                                plannedSegments: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tts-playback/exports/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        artifactId: string;
                        documentId: string;
                        documentVersion: number;
                        settingsHash: string;
                        /** @enum {string} */
                        format: "mp3" | "m4b";
                        speed: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            artifact: {
                                /** @enum {number} */
                                schemaVersion: 1;
                                artifactId: string;
                                sessionId: string;
                                storageUserId: string;
                                documentId: string;
                                documentVersion: number;
                                /** @enum {string} */
                                readerType: "pdf" | "epub" | "html";
                                settingsHash: string;
                                planObjectKey: string;
                                /** @enum {string} */
                                format: "mp3" | "m4b";
                                speed: number;
                                objectKey: string;
                                contentType: string;
                                byteLength: number;
                                dispositionFilename: string;
                                sourceSessionId: string;
                                sourcePlanObjectKey: string;
                                /** @enum {string} */
                                status: "ready";
                                createdAt: number;
                            } | null;
                            operation: {
                                opId: string;
                                subject: {
                                    /** @enum {string} */
                                    kind: "pdf_layout";
                                    documentId: string;
                                    namespace: string | null;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback";
                                    documentId: string;
                                    sessionId: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_plan";
                                    documentId: string;
                                    settingsHash: string;
                                    planSignature: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_export";
                                    documentId: string;
                                    artifactId: string;
                                    /** @enum {string} */
                                    format: "mp3" | "m4b";
                                } | {
                                    /** @enum {string} */
                                    kind: "document_preview";
                                    documentId: string;
                                    namespace: string | null;
                                    /** @enum {string} */
                                    previewKind: "card";
                                };
                                /** @enum {string} */
                                status: "queued" | "running" | "succeeded" | "failed";
                                queuedAt: number;
                                updatedAt: number;
                                startedAt?: number;
                                result?: unknown;
                                error?: {
                                    message: string;
                                    code?: string;
                                };
                                timing?: {
                                    queueWaitMs?: number;
                                    s3FetchMs?: number;
                                    computeMs?: number;
                                };
                                progress?: {
                                    totalPages: number;
                                    pagesParsed: number;
                                    currentPage?: number;
                                    /** @enum {string} */
                                    phase: "infer" | "merge";
                                } | {
                                    completedThroughOrdinal: number;
                                    completedCount: number;
                                    plannedCount: number;
                                } | {
                                    /** @enum {string} */
                                    phase: "assembling" | "transcoding" | "uploading";
                                    completedSegments: number;
                                    plannedSegments: number;
                                };
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pdf-layout/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        documentId: string;
                        namespace: string | null;
                        documentObjectKey: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            artifact: {
                                objectKey: string;
                            } | null;
                            operation: {
                                opId: string;
                                subject: {
                                    /** @enum {string} */
                                    kind: "pdf_layout";
                                    documentId: string;
                                    namespace: string | null;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback";
                                    documentId: string;
                                    sessionId: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_plan";
                                    documentId: string;
                                    settingsHash: string;
                                    planSignature: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_export";
                                    documentId: string;
                                    artifactId: string;
                                    /** @enum {string} */
                                    format: "mp3" | "m4b";
                                } | {
                                    /** @enum {string} */
                                    kind: "document_preview";
                                    documentId: string;
                                    namespace: string | null;
                                    /** @enum {string} */
                                    previewKind: "card";
                                };
                                /** @enum {string} */
                                status: "queued" | "running" | "succeeded" | "failed";
                                queuedAt: number;
                                updatedAt: number;
                                startedAt?: number;
                                result?: unknown;
                                error?: {
                                    message: string;
                                    code?: string;
                                };
                                timing?: {
                                    queueWaitMs?: number;
                                    s3FetchMs?: number;
                                    computeMs?: number;
                                };
                                progress?: {
                                    totalPages: number;
                                    pagesParsed: number;
                                    currentPage?: number;
                                    /** @enum {string} */
                                    phase: "infer" | "merge";
                                } | {
                                    completedThroughOrdinal: number;
                                    completedCount: number;
                                    plannedCount: number;
                                } | {
                                    /** @enum {string} */
                                    phase: "assembling" | "transcoding" | "uploading";
                                    completedSegments: number;
                                    plannedSegments: number;
                                };
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/document-previews/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        documentId: string;
                        namespace: string | null;
                        /** @enum {string} */
                        documentType: "pdf" | "epub";
                        sourceObjectKey: string;
                        sourceLastModifiedMs: number;
                        /** @enum {string} */
                        previewKind: "card";
                        rendererVersion?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            artifact: {
                                /** @enum {number} */
                                schemaVersion: 1;
                                documentId: string;
                                namespace: string | null;
                                /** @enum {string} */
                                documentType: "pdf" | "epub";
                                sourceObjectKey: string;
                                sourceLastModifiedMs: number;
                                /** @enum {string} */
                                previewKind: "card";
                                rendererVersion: string;
                                objectKey: string;
                                metadataObjectKey: string;
                                /** @enum {string} */
                                contentType: "image/jpeg";
                                width: number;
                                height: number | null;
                                byteLength: number;
                                eTag: string | null;
                                /** @enum {string} */
                                status: "ready";
                                createdAt: number;
                            } | null;
                            operation: {
                                opId: string;
                                subject: {
                                    /** @enum {string} */
                                    kind: "pdf_layout";
                                    documentId: string;
                                    namespace: string | null;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback";
                                    documentId: string;
                                    sessionId: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_plan";
                                    documentId: string;
                                    settingsHash: string;
                                    planSignature: string;
                                } | {
                                    /** @enum {string} */
                                    kind: "tts_playback_export";
                                    documentId: string;
                                    artifactId: string;
                                    /** @enum {string} */
                                    format: "mp3" | "m4b";
                                } | {
                                    /** @enum {string} */
                                    kind: "document_preview";
                                    documentId: string;
                                    namespace: string | null;
                                    /** @enum {string} */
                                    previewKind: "card";
                                };
                                /** @enum {string} */
                                status: "queued" | "running" | "succeeded" | "failed";
                                queuedAt: number;
                                updatedAt: number;
                                startedAt?: number;
                                result?: unknown;
                                error?: {
                                    message: string;
                                    code?: string;
                                };
                                timing?: {
                                    queueWaitMs?: number;
                                    s3FetchMs?: number;
                                    computeMs?: number;
                                };
                                progress?: {
                                    totalPages: number;
                                    pagesParsed: number;
                                    currentPage?: number;
                                    /** @enum {string} */
                                    phase: "infer" | "merge";
                                } | {
                                    completedThroughOrdinal: number;
                                    completedCount: number;
                                    plannedCount: number;
                                } | {
                                    /** @enum {string} */
                                    phase: "assembling" | "transcoding" | "uploading";
                                    completedSegments: number;
                                    plannedSegments: number;
                                };
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operations/{opId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    opId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            opId: string;
                            subject: {
                                /** @enum {string} */
                                kind: "pdf_layout";
                                documentId: string;
                                namespace: string | null;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback";
                                documentId: string;
                                sessionId: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_plan";
                                documentId: string;
                                settingsHash: string;
                                planSignature: string;
                            } | {
                                /** @enum {string} */
                                kind: "tts_playback_export";
                                documentId: string;
                                artifactId: string;
                                /** @enum {string} */
                                format: "mp3" | "m4b";
                            } | {
                                /** @enum {string} */
                                kind: "document_preview";
                                documentId: string;
                                namespace: string | null;
                                /** @enum {string} */
                                previewKind: "card";
                            };
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed";
                            queuedAt: number;
                            updatedAt: number;
                            startedAt?: number;
                            result?: unknown;
                            error?: {
                                message: string;
                                code?: string;
                            };
                            timing?: {
                                queueWaitMs?: number;
                                s3FetchMs?: number;
                                computeMs?: number;
                            };
                            progress?: {
                                totalPages: number;
                                pagesParsed: number;
                                currentPage?: number;
                                /** @enum {string} */
                                phase: "infer" | "merge";
                            } | {
                                completedThroughOrdinal: number;
                                completedCount: number;
                                plannedCount: number;
                            } | {
                                /** @enum {string} */
                                phase: "assembling" | "transcoding" | "uploading";
                                completedSegments: number;
                                plannedSegments: number;
                            };
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operations/{opId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    sinceEventId?: string | number;
                };
                header?: never;
                path: {
                    opId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server-sent ComputeOperationEvent stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ParsedPdfDocument: {
            /** @enum {number} */
            schemaVersion: 1;
            documentId: string;
            parserVersion: string;
            parsedAt: number;
            pages: {
                pageNumber: number;
                width: number;
                height: number;
                blocks: {
                    id: string;
                    /** @enum {string} */
                    kind: "abstract" | "algorithm" | "aside_text" | "chart" | "content" | "formula" | "doc_title" | "figure_title" | "footer" | "footnote" | "formula_number" | "header" | "image" | "number" | "paragraph_title" | "reference" | "reference_content" | "seal" | "table" | "text" | "vision_footnote";
                    fragments: {
                        page: number;
                        bbox: [
                            number,
                            number,
                            number,
                            number
                        ];
                        text: string;
                        readingOrder: number;
                        modelConfidence?: number;
                    }[];
                    text: string;
                    parentSectionId?: string;
                }[];
            }[];
        };
        TTSSentenceAlignment: {
            sentence: string;
            sentenceIndex: number;
            words: {
                text: string;
                startSec: number;
                endSec: number;
                charStart: number;
                charEnd: number;
            }[];
        };
        ArtifactReference: {
            objectKey: string;
        };
        ErrorResponse: {
            error: string;
        } & {
            [key: string]: unknown;
        };
        OperationError: {
            message: string;
            code?: string;
        };
        PdfLayoutProgress: {
            totalPages: number;
            pagesParsed: number;
            currentPage?: number;
            /** @enum {string} */
            phase: "infer" | "merge";
        };
        TtsPlaybackExportProgress: {
            /** @enum {string} */
            phase: "assembling" | "transcoding" | "uploading";
            completedSegments: number;
            plannedSegments: number;
        };
        TtsPlaybackExportArtifact: {
            /** @enum {number} */
            schemaVersion: 1;
            artifactId: string;
            sessionId: string;
            storageUserId: string;
            documentId: string;
            documentVersion: number;
            /** @enum {string} */
            readerType: "pdf" | "epub" | "html";
            settingsHash: string;
            planObjectKey: string;
            /** @enum {string} */
            format: "mp3" | "m4b";
            speed: number;
            objectKey: string;
            contentType: string;
            byteLength: number;
            dispositionFilename: string;
            sourceSessionId: string;
            sourcePlanObjectKey: string;
            /** @enum {string} */
            status: "ready";
            createdAt: number;
        };
        DocumentPreviewArtifact: {
            /** @enum {number} */
            schemaVersion: 1;
            documentId: string;
            namespace: string | null;
            /** @enum {string} */
            documentType: "pdf" | "epub";
            sourceObjectKey: string;
            sourceLastModifiedMs: number;
            /** @enum {string} */
            previewKind: "card";
            rendererVersion: string;
            objectKey: string;
            metadataObjectKey: string;
            /** @enum {string} */
            contentType: "image/jpeg";
            width: number;
            height: number | null;
            byteLength: number;
            eTag: string | null;
            /** @enum {string} */
            status: "ready";
            createdAt: number;
        };
        ComputeOperation: {
            opId: string;
            subject: {
                /** @enum {string} */
                kind: "pdf_layout";
                documentId: string;
                namespace: string | null;
            } | {
                /** @enum {string} */
                kind: "tts_playback";
                documentId: string;
                sessionId: string;
            } | {
                /** @enum {string} */
                kind: "tts_playback_plan";
                documentId: string;
                settingsHash: string;
                planSignature: string;
            } | {
                /** @enum {string} */
                kind: "tts_playback_export";
                documentId: string;
                artifactId: string;
                /** @enum {string} */
                format: "mp3" | "m4b";
            } | {
                /** @enum {string} */
                kind: "document_preview";
                documentId: string;
                namespace: string | null;
                /** @enum {string} */
                previewKind: "card";
            };
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            queuedAt: number;
            updatedAt: number;
            startedAt?: number;
            result?: unknown;
            error?: {
                message: string;
                code?: string;
            };
            timing?: {
                queueWaitMs?: number;
                s3FetchMs?: number;
                computeMs?: number;
            };
            progress?: {
                totalPages: number;
                pagesParsed: number;
                currentPage?: number;
                /** @enum {string} */
                phase: "infer" | "merge";
            } | {
                completedThroughOrdinal: number;
                completedCount: number;
                plannedCount: number;
            } | {
                /** @enum {string} */
                phase: "assembling" | "transcoding" | "uploading";
                completedSegments: number;
                plannedSegments: number;
            };
        };
        ComputeOperationEvent: {
            eventId: number;
            snapshot: {
                opId: string;
                subject: {
                    /** @enum {string} */
                    kind: "pdf_layout";
                    documentId: string;
                    namespace: string | null;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback";
                    documentId: string;
                    sessionId: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_plan";
                    documentId: string;
                    settingsHash: string;
                    planSignature: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_export";
                    documentId: string;
                    artifactId: string;
                    /** @enum {string} */
                    format: "mp3" | "m4b";
                } | {
                    /** @enum {string} */
                    kind: "document_preview";
                    documentId: string;
                    namespace: string | null;
                    /** @enum {string} */
                    previewKind: "card";
                };
                /** @enum {string} */
                status: "queued" | "running" | "succeeded" | "failed";
                queuedAt: number;
                updatedAt: number;
                startedAt?: number;
                result?: unknown;
                error?: {
                    message: string;
                    code?: string;
                };
                timing?: {
                    queueWaitMs?: number;
                    s3FetchMs?: number;
                    computeMs?: number;
                };
                progress?: {
                    totalPages: number;
                    pagesParsed: number;
                    currentPage?: number;
                    /** @enum {string} */
                    phase: "infer" | "merge";
                } | {
                    completedThroughOrdinal: number;
                    completedCount: number;
                    plannedCount: number;
                } | {
                    /** @enum {string} */
                    phase: "assembling" | "transcoding" | "uploading";
                    completedSegments: number;
                    plannedSegments: number;
                };
            };
        };
        PdfLayoutResolution: {
            artifact: {
                objectKey: string;
            } | null;
            operation: {
                opId: string;
                subject: {
                    /** @enum {string} */
                    kind: "pdf_layout";
                    documentId: string;
                    namespace: string | null;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback";
                    documentId: string;
                    sessionId: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_plan";
                    documentId: string;
                    settingsHash: string;
                    planSignature: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_export";
                    documentId: string;
                    artifactId: string;
                    /** @enum {string} */
                    format: "mp3" | "m4b";
                } | {
                    /** @enum {string} */
                    kind: "document_preview";
                    documentId: string;
                    namespace: string | null;
                    /** @enum {string} */
                    previewKind: "card";
                };
                /** @enum {string} */
                status: "queued" | "running" | "succeeded" | "failed";
                queuedAt: number;
                updatedAt: number;
                startedAt?: number;
                result?: unknown;
                error?: {
                    message: string;
                    code?: string;
                };
                timing?: {
                    queueWaitMs?: number;
                    s3FetchMs?: number;
                    computeMs?: number;
                };
                progress?: {
                    totalPages: number;
                    pagesParsed: number;
                    currentPage?: number;
                    /** @enum {string} */
                    phase: "infer" | "merge";
                } | {
                    completedThroughOrdinal: number;
                    completedCount: number;
                    plannedCount: number;
                } | {
                    /** @enum {string} */
                    phase: "assembling" | "transcoding" | "uploading";
                    completedSegments: number;
                    plannedSegments: number;
                };
            } | null;
        };
        TtsPlaybackExportArtifactResolution: {
            artifact: {
                /** @enum {number} */
                schemaVersion: 1;
                artifactId: string;
                sessionId: string;
                storageUserId: string;
                documentId: string;
                documentVersion: number;
                /** @enum {string} */
                readerType: "pdf" | "epub" | "html";
                settingsHash: string;
                planObjectKey: string;
                /** @enum {string} */
                format: "mp3" | "m4b";
                speed: number;
                objectKey: string;
                contentType: string;
                byteLength: number;
                dispositionFilename: string;
                sourceSessionId: string;
                sourcePlanObjectKey: string;
                /** @enum {string} */
                status: "ready";
                createdAt: number;
            } | null;
            operation: {
                opId: string;
                subject: {
                    /** @enum {string} */
                    kind: "pdf_layout";
                    documentId: string;
                    namespace: string | null;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback";
                    documentId: string;
                    sessionId: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_plan";
                    documentId: string;
                    settingsHash: string;
                    planSignature: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_export";
                    documentId: string;
                    artifactId: string;
                    /** @enum {string} */
                    format: "mp3" | "m4b";
                } | {
                    /** @enum {string} */
                    kind: "document_preview";
                    documentId: string;
                    namespace: string | null;
                    /** @enum {string} */
                    previewKind: "card";
                };
                /** @enum {string} */
                status: "queued" | "running" | "succeeded" | "failed";
                queuedAt: number;
                updatedAt: number;
                startedAt?: number;
                result?: unknown;
                error?: {
                    message: string;
                    code?: string;
                };
                timing?: {
                    queueWaitMs?: number;
                    s3FetchMs?: number;
                    computeMs?: number;
                };
                progress?: {
                    totalPages: number;
                    pagesParsed: number;
                    currentPage?: number;
                    /** @enum {string} */
                    phase: "infer" | "merge";
                } | {
                    completedThroughOrdinal: number;
                    completedCount: number;
                    plannedCount: number;
                } | {
                    /** @enum {string} */
                    phase: "assembling" | "transcoding" | "uploading";
                    completedSegments: number;
                    plannedSegments: number;
                };
            } | null;
        };
        DocumentPreviewResolution: {
            artifact: {
                /** @enum {number} */
                schemaVersion: 1;
                documentId: string;
                namespace: string | null;
                /** @enum {string} */
                documentType: "pdf" | "epub";
                sourceObjectKey: string;
                sourceLastModifiedMs: number;
                /** @enum {string} */
                previewKind: "card";
                rendererVersion: string;
                objectKey: string;
                metadataObjectKey: string;
                /** @enum {string} */
                contentType: "image/jpeg";
                width: number;
                height: number | null;
                byteLength: number;
                eTag: string | null;
                /** @enum {string} */
                status: "ready";
                createdAt: number;
            } | null;
            operation: {
                opId: string;
                subject: {
                    /** @enum {string} */
                    kind: "pdf_layout";
                    documentId: string;
                    namespace: string | null;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback";
                    documentId: string;
                    sessionId: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_plan";
                    documentId: string;
                    settingsHash: string;
                    planSignature: string;
                } | {
                    /** @enum {string} */
                    kind: "tts_playback_export";
                    documentId: string;
                    artifactId: string;
                    /** @enum {string} */
                    format: "mp3" | "m4b";
                } | {
                    /** @enum {string} */
                    kind: "document_preview";
                    documentId: string;
                    namespace: string | null;
                    /** @enum {string} */
                    previewKind: "card";
                };
                /** @enum {string} */
                status: "queued" | "running" | "succeeded" | "failed";
                queuedAt: number;
                updatedAt: number;
                startedAt?: number;
                result?: unknown;
                error?: {
                    message: string;
                    code?: string;
                };
                timing?: {
                    queueWaitMs?: number;
                    s3FetchMs?: number;
                    computeMs?: number;
                };
                progress?: {
                    totalPages: number;
                    pagesParsed: number;
                    currentPage?: number;
                    /** @enum {string} */
                    phase: "infer" | "merge";
                } | {
                    completedThroughOrdinal: number;
                    completedCount: number;
                    plannedCount: number;
                } | {
                    /** @enum {string} */
                    phase: "assembling" | "transcoding" | "uploading";
                    completedSegments: number;
                    plannedSegments: number;
                };
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
